#!/bin/bash

PRFX=/work/ecseak05/ecseak05/jaya/nektar_basic
NEKTAR_VERSION=5.6.0
NEKTAR_LABEL=nektar
NEKTAR_ARCHIVE=${NEKTAR_LABEL}-v${NEKTAR_VERSION}.tar.gz
NEKTAR_NAME=${NEKTAR_LABEL}-${NEKTAR_VERSION}
INSTALL_ROOT=${PRFX}/${NEKTAR_LABEL}/${NEKTAR_VERSION}
NEKTAR=${PRFX}/${NEKTAR_LABEL}/${NEKTAR_VERSION}/bin
NEK=${NEKTAR}
